[theme]
primaryColor = "#F63366"  # This is the color of the Button and Sliders
backgroundColor = "#FFFFFF" # Background color (White)
secondaryBackgroundColor = "#F0F2F6" # Sidebar color
textColor = "#262730" # Main text color
font = "sans serif"
